#!/usr/bin/env python3
"""Render the app icon: a radial aura behind the Δτ glyphs.

ONE source for both artifacts that have to match — the adaptive icon compiled into the APK
(a vector, so the gradient lives in XML) and the 512x512 PNG Play shows in the store. They are
generated from the same stop list here so they cannot drift apart, which is exactly what would
happen if the store icon were re-tinted in an image editor and the launcher icon left alone.

The glyphs are the existing foreground mipmap, composited unchanged: only the aura behind them
moves. Adaptive-icon geometry is 108dp with the glyph inside the 72dp safe zone, and the store
icon is the same art unmasked at 512.

    python3 tools/gen_icon.py --preview          # write candidates to the scratchpad, change nothing
    python3 tools/gen_icon.py --glow bright      # apply: rewrites the vector AND the 512 PNG
"""

import argparse
import os

from PIL import Image

FG = "app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png"
VECTOR = "app/src/main/res/drawable/ic_launcher_background.xml"
STORE = "docs/play-assets/icon-512.png"

# Each ramp is (offset, #RRGGBB) from the centre out. The core colour is what "tint" means; the
# spacing of the middle stops is what "glow" means — push the mid stop outward and the lit area
# grows instead of just getting brighter, which is what reads as bloom rather than a spotlight.
RAMPS = {
    # Shipping: no colour, no glow. A flat near-black tile and the white glyphs, nothing else.
    # Not pure #000 — a launcher masks this into a circle or squircle, and against a black
    # wallpaper on OLED a true-black tile has no silhouette at all.
    "flat": [(0.0, "0B0B0B"), (1.0, "0B0B0B")],
    # The original, for reference and for going back.
    "green": [(0.0, "16341F"), (0.55, "0B0B10"), (1.0, "060608")],
    # Blue, glow roughly as before — the conservative swap.
    "subtle": [(0.0, "123C5A"), (0.55, "0B0D14"), (1.0, "060608")],
    # Brighter core, wider mid — noticeably more lit without losing the near-black corners.
    "bright": [(0.0, "1B5E86"), (0.28, "13405C"), (0.62, "0A1420"), (1.0, "05070A")],
    # Maximum bloom: hot core, very wide falloff. Reads modern; risks looking washed at small sizes.
    "max": [(0.0, "2A7FB0"), (0.22, "1D5C85"), (0.50, "102A3E"), (0.78, "0A121B"), (1.0, "05070A")],
}

CENTER = (0.5, 0.463)  # centreX 54 / centreY 50 of 108, as the vector had it
RADIUS = 66 / 108


def lerp(a, b, t):
    return tuple(round(x + (y - x) * t) for x, y in zip(a, b))


def rgb(h):
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def render(ramp, size):
    """Radial gradient, sampled per pixel and linearly interpolated between stops."""
    stops = [(o, rgb(c)) for o, c in ramp]
    im = Image.new("RGB", (size, size))
    px = im.load()
    cx, cy = CENTER[0] * size, CENTER[1] * size
    r = RADIUS * size
    for y in range(size):
        for x in range(size):
            d = min((((x - cx) ** 2 + (y - cy) ** 2) ** 0.5) / r, 1.0)
            for i in range(len(stops) - 1):
                o0, c0 = stops[i]
                o1, c1 = stops[i + 1]
                if d <= o1 or i == len(stops) - 2:
                    t = 0.0 if o1 == o0 else min(max((d - o0) / (o1 - o0), 0.0), 1.0)
                    px[x, y] = lerp(c0, c1, t)
                    break
    return im


def compose(ramp, size=512):
    bg = render(ramp, size)
    fg = Image.open(FG).convert("RGBA").resize((size, size), Image.LANCZOS)
    bg.paste(fg, (0, 0), fg)
    return bg


def write_vector(ramp):
    items = "\n".join(
        f'                <item android:offset="{o}" android:color="#FF{c.upper()}" />'
        for o, c in ramp
    )
    open(VECTOR, "w").write(f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Near-black tile with a soft aura behind the glyphs, matching the app. Generated by
     tools/gen_icon.py — edit the ramp there, not here, so the 512 store icon stays in step. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path android:pathData="M0,0h108v108h-108z">
        <aapt:attr name="android:fillColor">
            <gradient
                android:type="radial"
                android:centerX="54"
                android:centerY="50"
                android:gradientRadius="66">
{items}
            </gradient>
        </aapt:attr>
    </path>
</vector>
''')


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--glow", choices=sorted(RAMPS), default="bright")
    ap.add_argument("--preview", action="store_true", help="render every ramp, change nothing")
    ap.add_argument("--out", default=".")
    a = ap.parse_args()

    if a.preview:
        for name, ramp in RAMPS.items():
            p = os.path.join(a.out, f"icon-{name}.png")
            compose(ramp).save(p)
            print(p)
    else:
        compose(RAMPS[a.glow]).save(STORE)
        write_vector(RAMPS[a.glow])
        print(f"{STORE} and {VECTOR} regenerated from ramp '{a.glow}'")
